spring:
  application:
    name: project-service

  datasource:
    url: jdbc:postgresql://localhost:5432/project-service
    username: postgres
    password: root1234
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  cloud:
    config:
      uri: http://localhost:8888

  mail:
    host: smtp.gmail.com
    port: 587
    username: nourghozzi9@gmail.com
    password: NOURgho28*
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8084
  servlet:
    context-path: /project-management

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

jwt:
  secret: MySuperSecretKeyWithMoreThan32Chars123!
  expiration: 86400000
  token:
    validity: 18000
    prefix: Bearer
  signing:
    key: signingkey
  authorities:
    key: roles
  header:
    string: Authorization

logging:
  level:
    org:
      springframework:
        security:
          oauth2: DEBUG
          oauth2.jwt: TRACE
    com:
      netflix:
        discovery: DEBUG
    org:
      springframework:
        cloud:
          netflix:
            eureka: DEBUG
